### ISSUE TITLE
ERROR: TypeError: Cannot set property '_meta' of undefined

### ISSUE THREAD

**Issue by Staicul** [sitespeedio/sitespeed.io#2348]
Hi,

Starting today, I am getting the following error:
```
[2019-02-25 15:54:52] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addExtrasToHAR (C:\Projects\sitespeed.io\node_modules\browsertime\lib\support\har\index.js:145:34)
    at addExtraFieldsToHar (C:\Projects\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:69:21)
    at Engine.runByScript (C:\Projects\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:167:7)
```

The issue can be reproduced using the following script:
```
module.exports = async function(context, commands) {
    await commands.navigate(
      'https://www.kolikkopelit.com'
    );
    
    try {
      await commands.wait.byXpath(`//a[@data-test-name="login-button"]`, 10);
      await commands.click.byXpath(`//a[@data-test-name="login-button"]`);

      await commands.wait.byXpath(`//*[@data-test-name="Modal-login"]`)
      await commands.addText.byXpath('testuser12_1@mailinator.com', `//input[@data-test-name="UsernameField"]`);
      await commands.addText.byXpath('passwordplaceholder', `//input[@data-test-name="PasswordField"]`);

      await commands.measure.start('login');
      await commands.click.byXpathAndWait(`//button[@data-test-name="EnabledLoginButton"]`);
      await commands.measure.stop();
    } catch (e) {
    }
  };
```

I am using sitespeed.io v 8.6.4 locally (Windows 10), the latest Chrome version: 72.0.3626.109 (Official Build) (64-bit). The script is run via the following command:
```
node bin/sitespeed.js test/login.js --multi
```

The log file is also attached.
[sitespeed.io.log](https://github.com/sitespeedio/sitespeed.io/files/2901083/sitespeed.io.log)

P.S.: The same script was running properly and yielding a proper report last week.

**Comment by soulgalore** [comment]
I wonder if the content change om the site and we don’t take of the change. I’m on vacation this week but will have a look later this week when I’m back online.

Best
Peter

**Comment by Staicul** [comment]
Wow, that was responsive. Nice! 👍
Additional info: if the measure.start() command is moved before the navigation, the error is not thrown.


Thanks!
Andrei

**Comment by soulgalore** [comment]
I wonder if the Google check is part of the problem:

<img width="473" alt="screen shot 2019-02-26 at 19 00 29" src="https://user-images.githubusercontent.com/540757/53435350-e5b49300-39f8-11e9-91d8-2a9810852e25.png">

Do you know if this was turned on before when it used to work? If you watch the screen when you run your test, do you see that everything looks ok or do can you see something special happening in one of the steps?


Best
Peter

**Comment by Staicul** [comment]
I never get the captcha now, but I don't think it's part of the problem, as it happened for it to pop up in the past and I was still able to get the report.
Nothing special happening in any of the steps, things are working as expected.

**Comment by luisxiaomai** [comment]
I also met this issue using `click.byXpathAndWait`

**Comment by soulgalore** [comment]
Hi @luisxiaomai could you create a separate issue showing how you run so we can reproduce, that would help us a lot! 
Thanks
Peter

**Comment by luisxiaomai** [comment]
@soulgalore my issue is due to the login submit click was not really triggered, I have fixed it. Thanks for your tools and ecosystem.

**Comment by Staicul** [comment]
Any updates on this one, @soulgalore ?

**Comment by soulgalore** [comment]
I never tried it after the captcha was gone, sorry I missed that.

**Comment by soulgalore** [comment]
I get the captcha on every try, I don't get the error. What does it look like for you?

**Comment by Staicul** [comment]
I still get the same error:

```
[2019-03-22 17:44:02] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addExtrasToHAR (/Users/vlasta/Projects/sitespeed.io/node_modules/browsertime/lib/support/har/index.js:145:34)
    at addExtraFieldsToHar (/Users/vlasta/Projects/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:69:21)
    at Engine.runByScript (/Users/vlasta/Projects/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:167:7)
```

I tried running from an external network and indeed the error is not there when you get captcha. I will talk to the team responsible for this and see whether they can deactivate the verification for that particular account. Will get back to you. Thanks!

**Comment by soulgalore** [comment]
Hmm strange, I should still have got it right? Its the script in https://github.com/sitespeedio/sitespeed.io/issues/2348#issue-414149852 ? I'll try again later today/tomorrow.

**Comment by guruannapantula** [comment]
Flow which works
- loading https://www.kolikkopelit.com
- *start the measurement*
- click on login button --> *a modal appears*
- enter credentials and click login
- stop the measurement ( url is the same )
- scroll down
- Start another measurement
- click logout
- stop measurement (same url)

Flow which doesn't work
- loading https://www.kolikkopelit.com
- click on login button --> *a modal appears*
- enter credentials
- *start measure*
- click login
- make sure user is logged in
- stop the measurement ( url is the same )
- scroll down
- Start another measurement
- click logout
- stop measurement (same url) (edited) 

In the second flow when I start the measurement I get the below error
login Button visible!, user is logged out
*****************login Script Execution Done!!**********************
[2019-03-22 20:19:21] ERROR: TypeError: Cannot set property '_meta' of undefined
   at Object.addExtrasToHAR (/usr/src/app/node_modules/browsertime/lib/support/har/index.js:145:34)
   at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:69:21)
   at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:173:7)
[2019-03-22 20:19:21] INFO: HTML stored in /sitespeed.io/sitespeed-result/login_docker_js/2019-03-22-20-18-54
**Something to do with starting the measurement, when there is a modal ?**

**Comment by soulgalore** [comment]
Hi @guruannapantula the `Cannot set property '_meta' of undefined` seems to happen If there's a missing page ... so I wonder when you login the page, does it generate a request? To be able to measure something it needs to generate a request. One way you could help me try, is to run with Firefox (since the HAR is generated in different ways).

Best
Peter

**Comment by soulgalore** [comment]
@Staicul can you guide me so I'm sure I run the same way as you do?

I use the exact script as in: https://github.com/sitespeedio/sitespeed.io/issues/2348#issue-414149852

And then run: `docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.8.1 script.js --multi`

Best
Peter

**Comment by guruannapantula** [comment]
checked on firefox and it works fine on Firefox! Only on chrome we get the Cannot set property '_meta' of undefined error

**Comment by Staicul** [comment]
Hi @soulgalore, since you would always get captcha after login (due to accessing the site from an external network), I was able to find another scenario that produces the error and does not require authentication. The script is the following:

```
module.exports = async function(context, commands) {
    await commands.navigate(
      'https://www.kolikkopelit.com'
    );
    
    try {
      await commands.wait.byXpath(`//a[@data-test-name="login-button"]`, 10);
      await commands.click.byXpath(`//a[@data-test-name="login-button"]`);
      await commands.wait.byXpath(`//*[@data-test-name="Modal-login"]`)
      await commands.measure.start('closemodal');
      await commands.click.byXpathAndWait(`//a[@data-test-name="close-link"]`);
      await commands.measure.stop();
    } catch (e) {
    }
  };
```

I run it locally with 
```
node bin/sitespeed.js test/script.js --multi -n=1
```
but I was able to get the error in the dockerized run as well. Please let me know if I can be of further assistance.

**Comment by Stegozaurus** [comment]
Hello @soulgalore! I get same error. It to happen if front-end implement "skeleton screens" pattern (that is page not loading but rendering new web-elements). Can sitespeed.io do measuring for skeleton screens? Or can in future?
I reproduce it on Google Chrome 72.0.3626.81 (it works fine on Firefox)

My script (i changed real domen and some personal data):

````
module.exports = async function(context, commands) {
  var testlogin = 'login';
  var testpassword = 'password';

  await commands.cache.clear();
  await commands.navigate('https://domen/catalog-list');
  await commands.js.run('document.cookie="contractor=00000";document.cookie="contractor_1=00000' + '"');

  try {
    //input login and password
    await commands.addText.bySelector(testlogin, 'form.src-components-FormAuth--form input[name="email"]');
    await commands.addText.bySelector(testpassword, 'form.src-components-FormAuth--form input[name="password"]');

    await commands.measure.start("Login");

    //press submit
    await commands.click.bySelectorAndWait('form.src-components-FormAuth--form button[type="submit"]');

    //wait until show specific element
    await commands.wait.byXpath('//button[text()="Иванов Иван Иванович"][@class="src-components-Header-HeaderTop--contractorButton"]', 20000);

    return commands.measure.stop();
  } catch (e) {
    console.error(e);
  } 
}; 
````

My run command:

`docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.9.0 --outputFolder output -n 1 --multi devopt1295.js`

Console output:

````
[2019-04-01 09:23:16] INFO: Versions OS: linux 4.9.0-8-amd64 nodejs: v10.13.0 sitespeed.io: 8.9.0 browsertime: 4.5.3 coach: 3.3.0
[2019-04-01 09:23:16] INFO: Running tests using Chrome - 1 iteration(s)
[2019-04-01 09:23:23] INFO: Navigating to url https://domen/catalog-list iteration 1
[2019-04-01 09:23:28] INFO: Start to measure Login
[2019-04-01 09:23:34] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addExtrasToHAR (/usr/src/app/node_modules/browsertime/lib/support/har/index.js:145:34)
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:69:21)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:173:7)
[2019-04-01 09:23:34] INFO: HTML stored in /sitespeed.io/output
````

**Comment by soulgalore** [comment]
Hi @Stegozaurus any chance you can share the full script with me peter [AT] soulgalore [dot] com, then I can have a look tonight. There's something wrong when [converting the Chrome trace log to the HAR file](https://github.com/sitespeedio/chrome-har) and it much easier to try to fix that if I have a concrete example.

Thanks!
Peter

**Comment by Staicul** [comment]
@soulgalore Weren't you able to reproduce with the script I provided?

**Comment by soulgalore** [comment]
@Staicul ah sorry I missed that, but on your script you try to measure closing a modal right, there's no new page load there?

**Comment by Staicul** [comment]
That's right, no new page load. But it should still work, right? The dockerized run with firefox is working.

**Comment by soulgalore** [comment]
Ah I see, you are looking it record a video and then get like lastVisualChange when the modal is closed? Right now it doesn't work as long as it generates a new page. 

When you say it works in Firefox, do you mean you don't get an error or do you get the metric you are looking for?

**Comment by Staicul** [comment]
When I said it works on Firefox, I meant that I'm not getting the error and it outputs the regular report, video included.
I wasn't looking for any metric with this script that closes the modal. I was just trying to provide you with a way to reproduce the error without authenticating, since you can't use the login script because of captcha. Hope it makes sense.

**Comment by soulgalore** [comment]
Ah I see @Staicul sorry I didn't get that. But is it really the same use case? It works like this in the background: We use the Chrome devtools protocol data to generate the HAR file (see https://github.com/sitespeedio/chrome-har), so even though the error looks the same in the error log (there's one page missing) the original error for you is probably caused that we are missing something in the data we try to parse to the HAR or parse it the wrong way, That's why it helps me to get the same example as for you what fails.

Another way to get that data (devtools log)  is by storing the log and then save it: --browsertime.chrome.collectPerfLog

Then we can rerun that against https://github.com/sitespeedio/chrome-har and try to see whats wrong.

Best
Peter

**Comment by Staicul** [comment]
[chromePerflog-1.json.gz](https://github.com/sitespeedio/sitespeed.io/files/3055195/chromePerflog-1.json.gz)

I have attached the perf log of a run that triggered the error after login. Please let me know if there is anything else I can do.

**Comment by junktest7** [comment]
I'm getting the same error while trying to track load time for page refresh where url stay the same throughout the whole ordering process. This requires several refresh of the page within same url, and I can't seem to be able to track more than one action at a time otherwise, it will complain: "has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs". I am adding an alias every time so that's not the issue and this message is just an INFO message, but it refuses to show any data, breaking with the same error as above. It would indeed be great if this refreshes within the same url could be supported, as our entire application works like that. :-(

**Comment by soulgalore** [comment]
Hi @junktest7 ,
I think it is several issues: The warning is fixed, but then it seems to be a bug somewhere then if it doesn't work for you.

The "cannot set property _meta" ... can mean many things so if you could create a new bug that would be super. Also if you could share how you run so I can reproduce that would be great: peter [at] soulgalore [dot] com.

Best
Peter

**Comment by junktest7** [comment]
Hi @soulgalore, thanks a lot for your answer. I ended up writing my own code to get page load time, and I can't just share my script since I'm working on a site I can't give you the password for. I will write a script for you on a demo site as soon as I am done with my current project and will share that with you then. Thanks a lot!

**Comment by soulgalore** [comment]
Cool.
