### ISSUE TITLE
Error reporting/dashboarding & Transaction/Alias pass/fail

### ISSUE THREAD

**Issue by jyoprakashJP** [sitespeedio/sitespeed.io#2418]
I have a question on error dashboarding, in case DOM elements are not found.

1.  Is there way to fail the login transaction/Alias (sample), same get reflected in the dashboard?
2. Alerting for those type of errors, where your response code is not >399?

**Sample:**
await commands.measure.start('login');
await commands.click.byIdAndWait('wpLoginAttempt');
await commands.wait.byId(**'1pt-userpage**',3000);
return commands.measure.stop();

I purposefully failed this transaction and in log I got this message **"ERROR: [browsertime.command.wait] Element by id 1pt-userpage was not located in 3000 ms"**

**Comment by soulgalore** [comment]
Hi @jyoprakashJP thanks for creating the issue. No there's no clean way today. In plugins we can send error messages (that then ends up in the HTML and should (but I need to verify) be able to get into the dashboards. 

But running your own script we don't support that ... however that seems to be something we should, let me think for a couple of days of how can support that In a good way, I'm thinking you probably wanna catch errors in the script but then also pass them on, without the full script to fail.

Best
Peter

**Comment by jyoprakashJP** [comment]
Sure,
Also, In my multistep script I would be validating each call with certain valid DOM/IDs,
if they are not found, I would rather fail it as my next step would result in error as well. example- if My login fails I should not be running remaining steps as it would generate errors and skewed response times for failed transaction

**Comment by soulgalore** [comment]
The current version of Browsertime is kind of broken for reporting errors per URL. I'll try to fix that tomorrow. I think it will work like this:
In your script, you can try/catch whatever you want. If you want to report an error, you can do that by adding it to context.errors array (or something like that), then you can report whatever meaningful error you want, and then I'll make sure sitespeed.io by default send the number of errors to Graphite/InfluxDB.

**Comment by jyoprakashJP** [comment]
do you have any sample?

**Comment by soulgalore** [comment]
I've pushed 8.13.0 and here are the small docs: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#error-handling

**Comment by jyoprakashJP** [comment]
Sure.
How I plan to run my script, I need to have validation for each step, if validation failes, I should fail that step, capture the failure, add it to dashboard for alert..

module.exports = async function(context, commands)
   {
  try{
  await commands.measure.start('loginPage');
  await commands.navigate('https://en.wikipedia.org/w/index.php?title=Special:UserLogin');
  await commands.wait.byId('wpLoginAttempt',2000);
  await commands.measure.stop();
  }
  catch(e)
  {
  return commands.measure.start('loginPage'); //Not sure if this is the correct way to fail the transaction
  process.exit(1); // if Step fails no point running the next step, exit the script,(eg if login fails, you can't perform next steps)
  //Other than this if I can add Error (e) as annotation or can log that into influxDB or grafana, would be easy for me to trigger alert, Mostly in case of non 4xx or 5xx error code
  }
  try {
         await commands.addText.byId('user','wpName1');
         await commands.addText.byId('password','wpPassword1');
         await commands.measure.start('login');
         await commands.click.byIdAndWait('wpLoginAttempt');
         await commands.wait.byId('pt-userpage',2000);
         await commands.measure.stop();
       }
       catch (e)
       {
	   return commands.measure.start('loginPage');
	   process.exit(1);
       }
   };

**Comment by jyoprakashJP** [comment]
Tried process.exit(1) and it stops the execution on error, but also, no test metrics/report htmls are generated.
If I can get html report for failed transaction, would be easy to troubleshoot in production (but I still don't want execute next step if 1st Step fails)

**Comment by soulgalore** [comment]
Yeah process.exit(1) will exit the node process = sitespeed.io will just stop. You can just throw the error and everything will be generated. However the error will not end up Graphite/InfluxDB at the moment. I had a quick look the other day and it needs some work to fix. I also wanna have something like commands.error(url, errorText) so you can add your own errors when things are missing/failing but that needs some refactoring.

**Comment by jyoprakashJP** [comment]
I tried something like below where next step would not execute if previous failed. Also, I am able to gather all metrics/result html for failed step. Only thing pending is capturing the error and sending to DB/dashboard as annotation or metrics.

catch (e)
       {
      return commands.measure.stop();
       process.exit(1);
       }

**Comment by soulgalore** [comment]
If you use process.exit you will end sitespeed.io, instead try to rethrow the error:

```
catch (e) {
   await commands.measure.stop();
   throw e
}
```

**Comment by Staicul** [comment]
Hi, @soulgalore . I was following the docs, to be more precise, this part:

You can also create your own errors. The error will be reported in the HTML and sent to Graphite/InfluxDB.
```
module.exports = async function(context, commands) {
  // ...
  try {
    // Click on a link
    await click.byLinkTextAndWait('Checkout');
  } catch (e) {
    // Oh no, the content team has changed the name of the link!
     commands.error('The link named Checkout do not exist on the page');
    // Since the error is reported, you can alert on it in Grafana
  }
};
```
but I had no success in finding the errors anywhere in InfluxDB.
After reading this issue, I got the feeling it is not implemented yet. Could you please shed more light on what is possible at the moment with regards to error handling?
Also, the "errors" metric value is always N/A, although a lot of my scripts fail due to errors.

**Comment by soulgalore** [comment]
Hi @Staicul I think then it is that the error aren't tagged correctly in InfluxDB (so they are not findable). Let us try to fix that. For Graphite they live in https://dashboard.sitespeed.io/d/000000059/page-timing-metrics?orgId=1&fullscreen&panelId=174

Best
Peter

**Comment by Staicul** [comment]
Hi, @soulgalore ! No need to spend time on this, I've figured it out. It was my fault, sorry. I was looking for the "value" field for errors, whereas errors only has the max, mean, median, min and p90 fields.
One question, still. Is it possible to get the custom error messages (from the commands.error command) into the db? It would be extremely useful.
