### ISSUE TITLE
Speed Index not calculated for localhost (docker)

### ISSUE THREAD

**Issue by AAZANOVICH** [sitespeedio/sitespeed.io#2859]
When running sitespeed.io in a docker container and testing website which is running on host machine (localhost) speed index is always zero.

>Exact how you run (the exact parameters)
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --video --speedIndex -c 3g -b chrome -n 3 https://host.docker.internal:9001 --mobile

>Which version you are using
Docker image info: Versions OS: linux 4.19.76-linuxkit nodejs: v12.13.0 sitespeed.io: 11.9.3 browsertime: 7.8.3 coach: 4.3.0

Repo with a code:
https://github.com/DanWahlin/Angular-HelloWorld
package.json start script "start": "ng serve --prod --port 9001 --ssl true"

Output:
Testing url https://host.docker.internal:9001 iteration 1
[2020-02-04 21:39:40] INFO: https://host.docker.internal:9001 BackEndTime: 15 DomInteractiveTime: 38 DomContentLoadedTime: 38 FirstPaint: 47 PageLoadTime: 39
[2020-02-04 21:39:40] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 ContentfulSpeedIndex: 0 LastVisualChange: 0
[2020-02-04 21:39:41] INFO: Testing url https://host.docker.internal:9001 iteration 2
[2020-02-04 21:39:49] INFO: https://host.docker.internal:9001 BackEndTime: 18 DomInteractiveTime: 39 DomContentLoadedTime: 39 FirstPaint: 51 PageLoadTime: 40
[2020-02-04 21:39:49] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 ContentfulSpeedIndex: 0 LastVisualChange: 0
[2020-02-04 21:39:49] INFO: Testing url https://host.docker.internal:9001 iteration 3

**Comment by soulgalore** [comment]
Hi @AAZANOVICH thanks for reporting. Hopefully this is automatically fixed in the next release (12 stable), there has been so many changes the last months. I'll ping the issue when the release is out there.

**Comment by AAZANOVICH** [comment]
@AAZANOVICH ok great, will be waiting !

**Comment by soulgalore** [comment]
Now you can try with latest 12.0.0, if you still have the problem I will take a look and try to reproduce.

**Comment by AAZANOVICH** [comment]
Will do testing today

**Comment by AAZANOVICH** [comment]
Still not working
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:12.0.1 --video --speedIndex -c 3g -b chrome -n 1 http://host.docker.internal:9000 --mobile
Google Chrome 80.0.3987.87 
Mozilla Firefox 72.0
[2020-02-11 00:17:26] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.13.0 sitespeed.io: 12.0.1 browsertime: 8.0.1 coach: 4.4.0
[2020-02-11 00:17:27] INFO: Running tests using Chrome - 1 iteration(s)
[2020-02-11 00:17:27] INFO: Testing url http://host.docker.internal:9000 iteration 1
[2020-02-11 00:17:38] INFO: http://host.docker.internal:9000 2 requests, backEndTime: 23ms, firstPaint: 74ms, firstVisualChange: 0ms, DOMContentLoaded: 55ms, Load: 57ms, speedIndex: 0, perceptualSpeedIndex: 0, contentfulSpeedIndex: 0, visualComplete85: 0ms, lastVisualChange: 0ms, rumSpeedIndex: 74
[2020-02-11 00:17:41] INFO: HTML stored in /sitespeed.io/sitespeed-result/host.docker.internal/2020-02-11-00-17-26

**Comment by soulgalore** [comment]
@AAZANOVICH can you check the screenshot and the video and check if they look ok? When I tried it against running the sitespeed.io documentation locally, it works for me™.

```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:12.0.1 --video --speedIndex -b chrome -n 1 http://host.docker.internal:4000 --mobile
Google Chrome 80.0.3987.87 
Mozilla Firefox 72.0
[2020-02-12 09:06:56] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.13.0 sitespeed.io: 12.0.1 browsertime: 8.0.1 coach: 4.4.0
[2020-02-12 09:06:57] INFO: Running tests using Chrome - 1 iteration(s)
[2020-02-12 09:06:58] INFO: Testing url http://host.docker.internal:4000 iteration 1
[2020-02-12 09:07:12] INFO: http://host.docker.internal:4000 13 requests, backEndTime: 14ms, firstPaint: 299ms, firstVisualChange: 300ms, DOMContentLoaded: 72ms, Load: 265ms, speedIndex: 300, perceptualSpeedIndex: 322, contentfulSpeedIndex: 300, visualComplete85: 300ms, lastVisualChange: 1.94s, rumSpeedIndex: 299
[2020-02-12 09:07:13] INFO: HTML stored in /sitespeed.io/sitespeed-result/host.docker.internal/2020-02-12-09-06-56
```

**Comment by AAZANOVICH** [comment]
@soulgalore 

$ docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:12.0.1 --video --speedIndex -b chrome -n 1 http://host.docker.internal:9001 --mobile
Google Chrome 80.0.3987.87 
Mozilla Firefox 72.0
[2020-02-13 19:59:18] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.13.0 sitespeed.io: 12.0.1 browsertime: 8.0.1 coach: 4.4.0
[2020-02-13 19:59:18] INFO: Running tests using Chrome - 1 iteration(s)
[2020-02-13 19:59:19] INFO: Testing url http://host.docker.internal:9001 iteration 1
[2020-02-13 19:59:43] ERROR: Could not add meta data to the HAR, miss page 0
[2020-02-13 19:59:43] INFO: http://host.docker.internal:9001 backEndTime: 14ms, firstPaint: 145ms, firstVisualChange: 200ms, DOMContentLoaded: 155ms, Load: 162ms, speedIndex: 200, perceptualSpeedIndex: 200, contentfulSpeedIndex: 200, visualComplete85: 200ms, lastVisualChange: 233ms, rumSpeedIndex: 145
[2020-02-13 19:59:43] ERROR: Could not find the right index 0 for har for url http://host.docker.internal:9001 
[2020-02-13 19:59:43] ERROR: Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/webcoach/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/webcoach/lib/index.js:130:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:229:29)
[2020-02-13 19:59:44] INFO: HTML stored in /sitespeed.io/sitespeed-result/host.docker.internal/2020-02-1

**Comment by AAZANOVICH** [comment]
@soulgalore video is empty, if I look at "Waterfall" tab, I can see only 2 requests:
1) host.docker.internal:9001
2) host.docker.internal:9001/favicon.ico 
Both return 200 OK, but nothing else is loaded. 

However I was able to make it work by doing the following:
1) I ran container and resolved host.docker.internal ip address 
2) Ran sitespeed.io from within the container, but using IP address from 1) instead of host.docker.internal

It worked this way...
